"""empty message

Revision ID: 0b44936a63bf
Revises: 5ce0cd0ffd3d
Create Date: 2020-04-21 15:30:04.443402

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0b44936a63bf'
down_revision = '5ce0cd0ffd3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_images', 'pic')
    op.drop_column('user_images', 'pic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_images', sa.Column('pic', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('admin_images', sa.Column('pic', postgresql.BYTEA(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
