"""empty message

Revision ID: 845d48d779f0
Revises: e60ce1063e7a
Create Date: 2020-04-21 19:35:19.897841

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '845d48d779f0'
down_revision = 'e60ce1063e7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ratings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ratings', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('placeid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['placeid'], ['places.id'], name='ratings_placeid_fkey'),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], name='ratings_userid_fkey')
    )
    # ### end Alembic commands ###
