"""empty message

Revision ID: e60ce1063e7a
Revises: 78d083eb429c
Create Date: 2020-04-21 19:21:55.922460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e60ce1063e7a'
down_revision = '78d083eb429c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ratings', 'userid',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ratings', 'userid',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
