"""empty message

Revision ID: 09ac41d6a652
Revises: 5c57c311413d
Create Date: 2020-05-13 20:26:23.302560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09ac41d6a652'
down_revision = '5c57c311413d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symbol',
    sa.Column('symbol_id', sa.Text(), nullable=False),
    sa.Column('symbol_name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('symbol_id')
    )
    op.create_table('place_has_symbol',
    sa.Column('symbol_link', sa.Text(), nullable=False),
    sa.Column('place_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['symbol_link'], ['symbol.symbol_id'], ),
    sa.PrimaryKeyConstraint('symbol_link', 'place_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('place_has_symbol')
    op.drop_table('symbol')
    # ### end Alembic commands ###
