"""empty message

Revision ID: 2d0a26623a72
Revises: aa19efb4c529
Create Date: 2020-05-19 16:22:46.328252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d0a26623a72'
down_revision = 'aa19efb4c529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_place',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('placeid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['placeid'], ['places.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('userid', 'placeid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_place')
    # ### end Alembic commands ###
