"""empty message

Revision ID: 465bba7c9470
Revises: 2d0a26623a72
Create Date: 2020-05-19 16:27:41.317469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '465bba7c9470'
down_revision = '2d0a26623a72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_place', sa.Column('datetime', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_place', 'datetime')
    # ### end Alembic commands ###
