"""empty message

Revision ID: 5c57c311413d
Revises: 5ebca253ec97
Create Date: 2020-05-12 19:10:14.488879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c57c311413d'
down_revision = '5ebca253ec97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_images',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('placeid', sa.Integer(), nullable=True),
    sa.Column('imageid', sa.Text(), nullable=False),
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['placeid'], ['places.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('userid', 'imageid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_images')
    # ### end Alembic commands ###
