"""empty message

Revision ID: 5ebca253ec97
Revises: ff2fa5b42862
Create Date: 2020-05-12 19:09:19.071838

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5ebca253ec97'
down_revision = 'ff2fa5b42862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_images')
    op.drop_table('admin_images')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_images',
    sa.Column('placeid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('alt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('imageid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['placeid'], ['places.id'], name='admin_images_placeid_fkey'),
    sa.PrimaryKeyConstraint('imageid', name='admin_images_pkey')
    )
    op.create_table('user_images',
    sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('placeid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('alt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('imageid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['placeid'], ['places.id'], name='user_images_placeid_fkey'),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], name='user_images_userid_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('userid', 'imageid', name='user_images_pkey')
    )
    # ### end Alembic commands ###
