"""empty message

Revision ID: aa19efb4c529
Revises: 09ac41d6a652
Create Date: 2020-05-13 21:06:49.818325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa19efb4c529'
down_revision = '09ac41d6a652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place_has_symbol', sa.Column('symbol_id', sa.Text(), nullable=False))
    op.drop_constraint('place_has_symbol_symbol_link_fkey', 'place_has_symbol', type_='foreignkey')
    op.create_foreign_key(None, 'place_has_symbol', 'symbol', ['symbol_id'], ['symbol_id'])
    op.drop_column('place_has_symbol', 'symbol_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place_has_symbol', sa.Column('symbol_link', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'place_has_symbol', type_='foreignkey')
    op.create_foreign_key('place_has_symbol_symbol_link_fkey', 'place_has_symbol', 'symbol', ['symbol_link'], ['symbol_id'])
    op.drop_column('place_has_symbol', 'symbol_id')
    # ### end Alembic commands ###
