"""empty message

Revision ID: ff2fa5b42862
Revises: 0de80620ff09
Create Date: 2020-05-02 23:46:12.125920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff2fa5b42862'
down_revision = '0de80620ff09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('followers_followed_id_fkey', 'followers', type_='foreignkey')
    op.drop_constraint('followers_follower_id_fkey', 'followers', type_='foreignkey')
    op.create_foreign_key(None, 'followers', 'user', ['followed_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'followers', 'user', ['follower_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('ratings_userid_fkey', 'ratings', type_='foreignkey')
    op.create_foreign_key(None, 'ratings', 'user', ['userid'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_images_userid_fkey', 'user_images', type_='foreignkey')
    op.create_foreign_key(None, 'user_images', 'user', ['userid'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_images', type_='foreignkey')
    op.create_foreign_key('user_images_userid_fkey', 'user_images', 'user', ['userid'], ['id'])
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.create_foreign_key('ratings_userid_fkey', 'ratings', 'user', ['userid'], ['id'])
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.create_foreign_key('followers_follower_id_fkey', 'followers', 'user', ['follower_id'], ['id'])
    op.create_foreign_key('followers_followed_id_fkey', 'followers', 'user', ['followed_id'], ['id'])
    # ### end Alembic commands ###
